site_name: LGSVL Simulator

repo_url: https://github.com/lgsvl/simulator
site_author: LG Silicon Valley Lab
site_description: Automotive vehicle simulator from LG Silicon Valley Lab

docs_dir: Docs

theme: readthedocs

copyright: Copyright &copy; 2019 LG Electronics Inc.

google_analytics: ['UA-130546445-1','lgsvlsimulator.com/docs']

nav:
- 'Home': 'index.md'
- 'Quick start':
  - 'Getting started': 'getting-started.md'
  - 'Build instructions': 'build-instructions.md'
  - 'Keyboard shortcuts': 'keyboard-shortcuts.md'
  - 'Ground truth obstacles': 'perception-ground-truth.md'
  - 'Frequently asked questions': 'faq.md'
- 'Integration with AD':
  - 'Running with Autoware': 'autoware-instructions.md'
  - 'Running with Apollo 3.5': 'apollo3-5-instructions.md'
  - 'Running with Apollo 3.0': 'apollo-instructions.md'
  - 'Python API': 'python-api.md'
  - 'Python API Examples': 'api-quickstart-descriptions.md'
- 'Tutorials':
  - 'Map Annotation': 'map-annotation.md'
  - 'NPC Map Navigation': 'npc-map-navigation.md'
  - 'How to add a new ego vehicle': 'add-new-ego-vehicle.md'
  - 'How to create a simple ROS2-based AD stack': 'create-ros2-ad-stack.md'
